# Slightly silly message dictionary
# Auto Generated by robconfig at Thu Jan  7 17:29:22 2021
#

messageDict = {
'StopMotors': {'English': {'purpose': 'Set power to 0 in both motor channels', 'type': 'Operations', 'text': 'Stopping motors.'}}, 
'Volts': {'English': {'purpose': 'words', 'type': 'Monitor', 'text': 'Volts'}}, 
'MainBatt': {'English': {'purpose': 'words', 'type': 'Monitor', 'text': 'Main battery voltage is '}}, 
'AheadHalf': {'English': {'purpose': 'set power in both motors to 50% at 0 degrees', 'type': 'Operations', 'text': 'Moving ahead at half speed.'}}, 
'RightTurn': {'English': {'purpose': 'Set power to 20% forward in left motor and 20% reverse in right motor', 'type': 'Operations', 'text': 'Turning right.'}}, 
'Goodbye': {'English': {'purpose': 'Shutting down', 'type': 'Operations', 'text': 'Goodbye'}}, 
'Reverse': {'English': {'purpose': 'Set power in both motors to 20% reverse', 'type': 'Operations', 'text': 'Backing up.'}}, 
'Motor1Current': {'English': {'purpose': 'words', 'type': 'Monitor', 'text': 'Current in motor 1 is '}}, 
'LeftTurn': {'English': {'purpose': 'Set power to 20% forward in right motor and 20% reverse in left motor.', 'type': 'Operations', 'text': 'Turning left.'}}, 
'FlankIn3': {'English': {'purpose': 'set power to 100% at 0 degrees in both motors', 'type': 'Operations', 'text': 'Engaging flank speed in 3 seconds.'}}, 
'Amps': {'English': {'purpose': 'word Amps', 'type': 'words', 'text': 'Amps'}}, 
'Motor2Current': {'English': {'purpose': 'words', 'type': 'Monitor', 'text': 'Current in motor 2 is '}}, 
'InternalVoltage': {'English': {'purpose': 'words', 'type': 'Monitor', 'text': 'Microcontroller internal voltage is '}}, 
'/r/': {'English': {'purpose': '', 'type': 'Drive local operations', 'text': 'Command'}}, 
'Hello': {'English': {'purpose': 'Robot Greeting', 'type': 'Monitor', 'text': 'Hello'}}, 
'AheadFull': {'English': {'purpose': 'set power in both motors to 75% at 0 degrees', 'type': 'Operations', 'text': 'Moving ahead at full speed.'}}, 
'Volt': {'English': {'purpose': 'words', 'type': 'Monitor', 'text': 'Volt'}}, 
'AheadSlow': {'English': {'purpose': 'Set power to 20% at 0 degrees', 'type': 'Operations', 'text': 'Moving ahead slowly.'}}, 
'Amp': {'English': {'purpose': 'word Amp', 'type': 'words', 'text': 'Amps'}}, 
}
