# Slightly silly message dictionary
# Auto Generated by robconfig at Sun Feb 26 21:45:34 2023
#

messageDict = {
'/r/': {'English': {'text': 'Command', 'purpose': '', 'type': 'Drive local operations'}}, 
'AheadFull': {'English': {'text': 'Moving ahead at full speed.', 'purpose': 'set power in both motors to 75% at 0 degrees', 'type': 'Operations'}}, 
'AheadHalf': {'English': {'text': 'Moving ahead at half speed.', 'purpose': 'set power in both motors to 50% at 0 degrees', 'type': 'Operations'}}, 
'AheadSlow': {'English': {'text': 'Moving ahead slowly.', 'purpose': 'Set power to 20% at 0 degrees', 'type': 'Operations'}}, 
'Amp': {'English': {'text': 'Amps', 'purpose': 'word Amp', 'type': 'words'}}, 
'Amps': {'English': {'text': 'Amps', 'purpose': 'word Amps', 'type': 'words'}}, 
'FlankIn3': {'English': {'text': 'Engaging flank speed in 3 seconds.', 'purpose': 'set power to 100% at 0 degrees in both motors', 'type': 'Operations'}}, 
'Goodbye': {'English': {'text': 'Goodbye', 'purpose': 'Shutting down', 'type': 'Operations'}}, 
'Hello': {'English': {'text': 'Hello', 'purpose': 'Robot Greeting', 'type': 'Monitor'}}, 
'InternalVoltage': {'English': {'text': 'Microcontroller internal voltage is ', 'purpose': 'words', 'type': 'Monitor'}}, 
'LeftTurn': {'English': {'text': 'Turning left.', 'purpose': 'Set power to 20% forward in right motor and 20% reverse in left motor.', 'type': 'Operations'}}, 
'MainBatt': {'English': {'text': 'Main battery voltage is ', 'purpose': 'words', 'type': 'Monitor'}}, 
'Motor1Current': {'English': {'text': 'Current in motor 1 is ', 'purpose': 'words', 'type': 'Monitor'}}, 
'Motor2Current': {'English': {'text': 'Current in motor 2 is ', 'purpose': 'words', 'type': 'Monitor'}}, 
'Reverse': {'English': {'text': 'Backing up.', 'purpose': 'Set power in both motors to 20% reverse', 'type': 'Operations'}}, 
'RightTurn': {'English': {'text': 'Turning right.', 'purpose': 'Set power to 20% forward in left motor and 20% reverse in right motor', 'type': 'Operations'}}, 
'StopMotors': {'English': {'text': 'Stopping motors.', 'purpose': 'Set power to 0 in both motor channels', 'type': 'Operations'}}, 
'Volt': {'English': {'text': 'Volt', 'purpose': 'words', 'type': 'Monitor'}}, 
'Volts': {'English': {'text': 'Volts', 'purpose': 'words', 'type': 'Monitor'}}, 
}
