# message dictionary
# Auto Generated by Robconfig: Wed Mar 11 01:55:21 2020
#
messageDict = {
	'Reverse': ('English', 'Backing up.', 'Set power in both motors to 20% reverse', 'Operations'),
	'RightTurn': ('English', 'Turning right.', 'Set power to 20% forward in left motor and 20% reverse in right motor', 'Operations'),
	'AheadSlow': ('English', 'Moving ahead slowly.', 'Set power to 20% at 0 degrees', 'Operations'),
	'StopMotors': ('English', 'Stopping motors.', 'Set power to 0 in both motor channels', 'Operations'),
	'/r/': ('English', 'Command', '', 'Drive local operations'),
	'LeftTurn': ('English', 'Turning left.', 'Set power to 20% forward in right motor and 20% reverse in left motor.', 'Operations'),
	'Hello': ('English', 'Hello', 'Robot Greeting', 'Monitor'),
	'Volts': ('English', 'Volts', 'words', 'Monitor'),
	'Motor2Current': ('English', 'Current in motor 2 is ', 'words', 'Monitor'),
	'MainBatt': ('English', 'Main battery voltage is ', 'words', 'Monitor'),
	'InternalVoltage': ('English', 'Microcontroller internal voltage is ', 'words', 'Monitor'),
	'FlankIn3': ('English', 'Engaging flank speed in 3 seconds.', 'set power to 100% at 0 degrees in both motors', 'Operations'),
	'AheadFull': ('English', 'Moving ahead at full speed.', 'set power in both motors to 75% at 0 degrees', 'Operations'),
	'Motor1Current': ('English', 'Current in motor 1 is ', 'words', 'Monitor'),
	'Amp': ('English', 'Amps', 'word Amp', 'words'),
	'AheadHalf': ('English', 'Moving ahead at half speed.', 'set power in both motors to 50% at 0 degrees', 'Operations'),
	'Volt': ('English', 'Volt', 'words', 'Monitor'),
	'Amps': ('English', 'Amps', 'word Amps', 'words')
	}
